from .base import *

CELERY_BROKER_URL = RABBIT_URI
CELERY_RESULT_BACKEND = REDIS_LINK
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
