from config.sett1ngs.base import *
from config.sett1ngs.debug import *
from config.sett1ngs.database import *
from config.sett1ngs.cache import *
from config.sett1ngs.security import *
from config.sett1ngs.application import *
from config.sett1ngs.channels import *
from config.sett1ngs.internationalization import *
from config.sett1ngs.rest_framework import *
from config.sett1ngs.celery import *
